//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MD_CERVEJA_AGORA : DbContext
    {
        public MD_CERVEJA_AGORA()
            : base("name=MD_CERVEJA_AGORA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TB_CAD_COMENTARIO> TB_CAD_COMENTARIO { get; set; }
        public virtual DbSet<TB_CAD_DISTRIBUIDORA> TB_CAD_DISTRIBUIDORA { get; set; }
        public virtual DbSet<TB_CAD_PRODUTO> TB_CAD_PRODUTO { get; set; }
        public virtual DbSet<TB_CAD_TIPO_PRODUTO> TB_CAD_TIPO_PRODUTO { get; set; }
        public virtual DbSet<TB_CAD_USUARIO> TB_CAD_USUARIO { get; set; }
        public virtual DbSet<TB_END_BAIRRO> TB_END_BAIRRO { get; set; }
        public virtual DbSet<TB_END_CIDADE> TB_END_CIDADE { get; set; }
        public virtual DbSet<TB_END_ENDERECO> TB_END_ENDERECO { get; set; }
        public virtual DbSet<TB_END_TIPO_ENDERECO> TB_END_TIPO_ENDERECO { get; set; }
        public virtual DbSet<TB_END_UF> TB_END_UF { get; set; }
        public virtual DbSet<TB_PED_PEDIDO> TB_PED_PEDIDO { get; set; }
        public virtual DbSet<TB_PED_PEDIDO_PRODUTO> TB_PED_PEDIDO_PRODUTO { get; set; }
        public virtual DbSet<TB_PED_SITUACAO_PEDIDO> TB_PED_SITUACAO_PEDIDO { get; set; }
        public virtual DbSet<TB_SEG_PERFIL> TB_SEG_PERFIL { get; set; }
    }
}
