//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAD_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CAD_PRODUTO()
        {
            this.TB_CAD_COMENTARIO = new HashSet<TB_CAD_COMENTARIO>();
            this.TB_PED_PEDIDO_PRODUTO = new HashSet<TB_PED_PEDIDO_PRODUTO>();
        }
    
        public int CD_PRODUTO { get; set; }
        public int CD_DISTRIBUIDORA { get; set; }
        public int CD_TIPO_PRODUTO { get; set; }
        public string NM_PRODUTO { get; set; }
        public Nullable<decimal> VL_VALOR_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public System.TimeSpan HR_ENTREGA_PRODUTO { get; set; }
        public Nullable<bool> FL_VISIVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CAD_COMENTARIO> TB_CAD_COMENTARIO { get; set; }
        public virtual TB_CAD_TIPO_PRODUTO TB_CAD_TIPO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PED_PEDIDO_PRODUTO> TB_PED_PEDIDO_PRODUTO { get; set; }
    }
}
