//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAD_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CAD_USUARIO()
        {
            this.TB_CAD_COMENTARIO = new HashSet<TB_CAD_COMENTARIO>();
            this.TB_END_ENDERECO = new HashSet<TB_END_ENDERECO>();
            this.TB_PED_PEDIDO = new HashSet<TB_PED_PEDIDO>();
            this.TB_SEG_PERFIL = new HashSet<TB_SEG_PERFIL>();
        }
    
        public int CD_USUARIO { get; set; }
        public Nullable<short> CD_PERFIL { get; set; }
        public string NM_USUARIO { get; set; }
        public string DS_EMAIL { get; set; }
        public string DS_SENHA { get; set; }
        public Nullable<bool> FL_ATIVO { get; set; }
        public byte[] IMG_FOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CAD_COMENTARIO> TB_CAD_COMENTARIO { get; set; }
        public virtual TB_CAD_DISTRIBUIDORA TB_CAD_DISTRIBUIDORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_END_ENDERECO> TB_END_ENDERECO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PED_PEDIDO> TB_PED_PEDIDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SEG_PERFIL> TB_SEG_PERFIL { get; set; }
    }
}
