//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_END_ENDERECO
    {
        public short CD_ENDERECO { get; set; }
        public int CD_USUARIO { get; set; }
        public int CD_CIDADE { get; set; }
        public short CD_UF { get; set; }
        public Nullable<short> CD_TIPO_ENDERECO { get; set; }
        public Nullable<int> CD_BAIRRO { get; set; }
        public Nullable<bool> FL_ENDERECO_PADRAO { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string CEP { get; set; }
        public System.DateTime DT_ATUALIZACAO { get; set; }
    
        public virtual TB_CAD_USUARIO TB_CAD_USUARIO { get; set; }
        public virtual TB_END_BAIRRO TB_END_BAIRRO { get; set; }
        public virtual TB_END_CIDADE TB_END_CIDADE { get; set; }
        public virtual TB_END_TIPO_ENDERECO TB_END_TIPO_ENDERECO { get; set; }
        public virtual TB_END_UF TB_END_UF { get; set; }
    }
}
