//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_END_CIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_END_CIDADE()
        {
            this.TB_END_ENDERECO = new HashSet<TB_END_ENDERECO>();
        }
    
        public int CD_CIDADE { get; set; }
        public short CD_UF { get; set; }
        public string NM_CIDADE { get; set; }
    
        public virtual TB_END_UF TB_END_UF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_END_ENDERECO> TB_END_ENDERECO { get; set; }
    }
}
