//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD_RESTFULL_NEGOCIO.Pesistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PED_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PED_PEDIDO()
        {
            this.TB_PED_PEDIDO_PRODUTO = new HashSet<TB_PED_PEDIDO_PRODUTO>();
        }
    
        public int CD_PEDIDO { get; set; }
        public short CD_SITUACAO_PEDIDO { get; set; }
        public int CD_USUARIO { get; set; }
        public string NR_PEDIDO { get; set; }
        public System.DateTime DT_PEDIDO { get; set; }
        public decimal VL_PEDIDO { get; set; }
        public Nullable<decimal> VL_VALOR_FRETE { get; set; }
        public decimal VL_VALOR_TOTAL_PEDIDO { get; set; }
    
        public virtual TB_CAD_USUARIO TB_CAD_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PED_PEDIDO_PRODUTO> TB_PED_PEDIDO_PRODUTO { get; set; }
        public virtual TB_PED_SITUACAO_PEDIDO TB_PED_SITUACAO_PEDIDO { get; set; }
    }
}
